name: ${project.name}
main: mc.alk.arena.BattleArena
version: ${project.version}
website: http://dev.bukkit.org/bukkit-plugins/battlearena2/
description: Arena system for BattleCraft
authors: [alkarin, Europia79]
softdepend: [BattleTracker-lite, Essentials, Herochat, Heroes, IcePvPControl, Factions, GroupManager, mcMMO, MultiInv, Multiworld, Multiverse-Core, Multiverse-Inventories, PvPToggle, PvPTime, PvPTimer, SimpleClans, TagAPI, Towny, WorldEdit, WorldGuard, VanishNoPackes, Vault]
commands:
    arenaScoreboard:
        aliases: [sb]
        description: Scoreboard commands
        usage: /sb create | setmax | add
    arenateam:
        aliases: [team,at]
        description: Team commands
    arena:
        aliases: [a]
        description: Arena commands
    skirmish:
        aliases: [sk]
        description: Skirmish commands
    battleground:
        aliases: [bg]
        description: battleground commands
    watch:
        description: watch a fight
    tourney:
        description: Create a tournament
    colosseum:
        aliases: [col]
        description: colosseum commands
    freeforall:
        aliases: [ffa]
        description: join a ffa
    deathMatch:
        aliases: [dm]
        description: join a dm
    arenaAlter:
        aliases: [arenaEdit,aa]
    battleArena:
        aliases: [ba]
        description: Admin commands
    battleArenaDebug:
        aliases: [bad]
        description: Debugging Commands
    battleArenaScheduler:
        aliases: [bas]
        description: Schedule Continuous Events
    battleTracker:
        aliases: [bt]
        description: Show help menu
        usage: /bt
    btpvp:
        aliases: [pvp]
        description: Show how players have matched up
        usage: /pvp player1 [player2]
    btpve:
        aliases: [pve]
        description: Show how players have matched up vs mobs/environment
        usage: /pve player1 [player2]
permissions:
    battlearena.admin:
        default: op
        children:
            arena.admin: true
    battlearena.join:
        default: true
        children:
            arena.leave: true
            arena.join.arena: true
            arena.join.team.all: true
            arena.join.battleground: true
            arena.join.colosseum: true
            arena.join.deathmatch: true
            arena.join.freeforall: true
            arena.join.skirmish: true
            arena.join.tourney: true
